In [9]:
""" 
Notebook which demonstrates: 
1. Concept of Broadcasting
2. Numpy vectors in detail
"""

# Broadcasting
# Ex. A = np.dot(W.T, X) + b
# b becomes a 1*m vector consisting of all values as b

import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [10]:
total_cal = A.sum(axis=0)
print(total_cal.shape, total_cal)

(4,) [ 59.  239.  155.4  76.9]


In [11]:
percentage_A = 100 * A/total_cal.reshape(1,4)
percentage_A

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [13]:
# Numpy Vectors
a = np.random.randn(5) # This creates a rank one array, neither a row vector nor a column vector
print(a, '\n', a.shape)

[ 0.40011303  1.3872518   1.3683324   0.91436865 -0.81943912] 
 (5,)


In [14]:
print(a.T.shape) # Transpose of a rank one array returns same array

(5,)


In [17]:
print(np.dot(a, a.T)) # This doesn't give outer product

5.464442039864193


In [18]:
# To create a row or column vector use this
a = np.random.randn(5,1)
print(a) # This is a column vector

[[ 0.77008083]
 [-0.44570056]
 [-0.06833898]
 [ 0.14298079]
 [ 0.29211476]]


In [20]:
print(a.T) # This is a row vector

[[ 0.77008083 -0.44570056 -0.06833898  0.14298079  0.29211476]]


In [22]:
print(np.dot(a, a.T)) # This gives a outer product

[[ 0.59302448 -0.34322546 -0.05262654  0.11010677  0.22495198]
 [-0.34322546  0.19864899  0.03045872 -0.06372662 -0.13019571]
 [-0.05262654  0.03045872  0.00467022 -0.00977116 -0.01996282]
 [ 0.11010677 -0.06372662 -0.00977116  0.02044351  0.0417668 ]
 [ 0.22495198 -0.13019571 -0.01996282  0.0417668   0.08533103]]


In [0]:
assert(a.shape == (5,1)) # Raises an assertion error if condition is false